spring.application.name=metereagle-api
spring.datasource.url=jdbc:postgresql://192.168.0.83:5432/metereagle
spring.datasource.username=postgres
spring.datasource.password=unity0216
spring.jpa.hibernate.ddl-auto=validate
